export const comments = [
  {
    id: 1,
    postId: 1,
    author: { id: 1, name: "John Doe", email: "john@example.com" },
    content: "This is a great article about frontend development!",
    createdAt: "2025-05-27T11:00:00.000Z",
  },
  {
    id: 2,
    postId: 2,
    author: { id: 2, name: "Jane Smith", email: "jane@example.com" },
    content: "Backend development is indeed crucial for scalability.",
    createdAt: "2025-05-26T12:00:00.000Z",
  },
  {
    id: 3,
    postId: 3,
    author: { id: 3, name: "Alice Johnson", email: "alice@example.com" },
    content: "AI is transforming the way we approach software development.",
    createdAt: "2025-05-25T13:00:00.000Z",
  },
  {
    id: 4,
    postId: 4,
    author: { id: 4, name: "Michael Brown", email: "michael@example.com" },
    content: "Full stack development is the future of web applications.",
    createdAt: "2025-05-24T14:00:00.000Z",
  },
  {
    id: 5,
    postId: 5,
    author: { id: 5, name: "Emily Davis", email: "emily@example.com" },
    content: "Programming languages are evolving rapidly in 2025.",
    createdAt: "2025-05-23T15:00:00.000Z",
  },
  {
    id: 6,
    postId: 6,
    author: { id: 6, name: "Chris Evans", email: "chris@example.com" },
    content: "Cloud computing offers scalability and flexibility for businesses.",
    createdAt: "2025-05-22T16:00:00.000Z",
  },
  {
    id: 7,
    postId: 7,
    author: { id: 7, name: "Sophia Lee", email: "sophia@example.com" },
    content: "Building scalable web applications is a must in 2025.",
    createdAt: "2025-05-21T17:00:00.000Z",
  },
  {
    id: 8,
    postId: 8,
    author: { id: 8, name: "David Miller", email: "david@example.com" },
    content: "Cybersecurity is critical as threats continue to evolve.",
    createdAt: "2025-05-20T18:00:00.000Z",
  },
  {
    id: 9,
    postId: 9,
    author: { id: 9, name: "Olivia Taylor", email: "olivia@example.com" },
    content: "DevOps ensures faster delivery and better collaboration.",
    createdAt: "2025-05-19T19:00:00.000Z",
  },
  {
    id: 10,
    postId: 10,
    author: { id: 10, name: "Liam Wilson", email: "liam@example.com" },
    content: "AI is revolutionizing industries like healthcare and finance.",
    createdAt: "2025-05-18T20:00:00.000Z",
  },
  {
    id: 11,
    postId: 1,
    author: { id: 11, name: "Ella Martinez", email: "ella@example.com" },
    content: "Frontend development is becoming more accessible to beginners.",
    createdAt: "2025-05-27T21:00:00.000Z",
  },
  {
    id: 12,
    postId: 2,
    author: { id: 12, name: "Daniel Garcia", email: "daniel@example.com" },
    content: "Backend frameworks are improving scalability and performance.",
    createdAt: "2025-05-26T22:00:00.000Z",
  },
  {
    id: 13,
    postId: 3,
    author: { id: 13, name: "Mia Hernandez", email: "mia@example.com" },
    content: "AI tools are making software development faster and smarter.",
    createdAt: "2025-05-25T23:00:00.000Z",
  },
  {
    id: 14,
    postId: 4,
    author: { id: 14, name: "Lucas Martinez", email: "lucas@example.com" },
    content: "Full stack developers are in high demand in 2025.",
    createdAt: "2025-05-24T10:00:00.000Z",
  },
  {
    id: 15,
    postId: 5,
    author: { id: 15, name: "Isabella Lopez", email: "isabella@example.com" },
    content: "Learning new programming languages is essential for developers.",
    createdAt: "2025-05-23T11:00:00.000Z",
  },
  {
    id: 16,
    postId: 6,
    author: { id: 16, name: "Ethan Clark", email: "ethan@example.com" },
    content: "Cloud computing is transforming the way businesses operate.",
    createdAt: "2025-05-22T12:00:00.000Z",
  },
  {
    id: 17,
    postId: 7,
    author: { id: 17, name: "Ava Rodriguez", email: "ava@example.com" },
    content: "Scalable web applications are key to handling large user bases.",
    createdAt: "2025-05-21T13:00:00.000Z",
  },
  {
    id: 18,
    postId: 8,
    author: { id: 18, name: "Noah Davis", email: "noah@example.com" },
    content: "Cybersecurity measures are more important than ever.",
    createdAt: "2025-05-20T14:00:00.000Z",
  },
  {
    id: 19,
    postId: 9,
    author: { id: 19, name: "Emma White", email: "emma@example.com" },
    content: "DevOps practices are improving collaboration and efficiency.",
    createdAt: "2025-05-19T15:00:00.000Z",
  },
  {
    id: 20,
    postId: 10,
    author: { id: 20, name: "James Brown", email: "james@example.com" },
    content: "AI innovations are driving advancements in multiple industries.",
    createdAt: "2025-05-18T16:00:00.000Z",
  },
];