export const mostLikedPosts = {
  data: [
    {
      id: 11,
      title: "The Rise of AI in Software Development",
      content: "Artificial Intelligence is transforming the way software is developed, tested, and deployed.",
      tags: ["AI", "Software", "Development"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750634588/ai-image_gyreog.svg",
      author: { id: 3, name: "Alice Johnson", email: "alice@example.com" },
      createdAt: "2025-05-25T10:00:00.000Z",
      likes: 70,
      comments: 40,
    },
    {
      id: 12,
      title: "How to Master Full Stack Development in 2025",
      content: "Full stack development combines frontend and backend skills to create complete web applications.",
      tags: ["Full Stack", "Development", "Coding"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750634588/fullstack-image_gyreog.svg",
      author: { id: 4, name: "Michael Brown", email: "michael@example.com" },
      createdAt: "2025-05-24T10:00:00.000Z",
      likes: 35,
      comments: 15,
    },
    {
      id: 13,
      title: "The Future of Cloud Computing in 2025",
      content: "Cloud computing continues to evolve, offering scalability and flexibility for businesses worldwide.",
      tags: ["Cloud", "Computing", "Tech"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750634588/cloud-computing-image_gyreog.svg",
      author: { id: 6, name: "Chris Evans", email: "chris@example.com" },
      createdAt: "2025-05-22T10:00:00.000Z",
      likes: 45,
      comments: 18,
    },
    {
      id: 14,
      title: "The Importance of Cybersecurity in 2025",
      content: "Cybersecurity is more critical than ever as threats continue to evolve.",
      tags: ["Cybersecurity", "Tech", "Security"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750634588/cybersecurity-image_gyreog.svg",
      author: { id: 8, name: "David Miller", email: "david@example.com" },
      createdAt: "2025-05-20T10:00:00.000Z",
      likes: 25,
      comments: 10,
    },
    {
      id: 15,
      title: "The Role of DevOps in Modern Software Development",
      content: "DevOps bridges the gap between development and operations, ensuring faster delivery.",
      tags: ["DevOps", "Software", "Development"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750634588/devops-image_gyreog.svg",
      author: { id: 9, name: "Olivia Taylor", email: "olivia@example.com" },
      createdAt: "2025-05-19T10:00:00.000Z",
      likes: 40,
      comments: 20,
    },
  ],
  total: 5,
  page: 1,
  lastPage: 1,
};