export const myPosts = {
  data: [
    {
      id: 1,
      title: "My First Post",
      content: "This is the content of my first post.",
      tags: ["Welcome", "Intro"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-27T10:00:00.000Z",
      likes: 5,
      comments: 2,
    },
    {
      id: 2,
      title: "Exploring the World of Programming",
      content: "Programming opens up endless possibilities for innovation.",
      tags: ["Programming", "Innovation"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-26T10:00:00.000Z",
      likes: 10,
      comments: 4,
    },
    {
      id: 3,
      title: "The Beauty of Frontend Development",
      content: "Frontend development is all about creating amazing user experiences.",
      tags: ["Frontend", "UX"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-25T10:00:00.000Z",
      likes: 15,
      comments: 5,
    },
    {
      id: 4,
      title: "Backend Development Essentials",
      content: "Backend development ensures the functionality of web applications.",
      tags: ["Backend", "Web"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-24T10:00:00.000Z",
      likes: 8,
      comments: 3,
    },
    {
      id: 5,
      title: "Cloud Computing in Modern Tech",
      content: "Cloud computing offers scalability and flexibility for businesses.",
      tags: ["Cloud", "Tech"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-23T10:00:00.000Z",
      likes: 12,
      comments: 6,
    },
    {
      id: 6,
      title: "The Importance of Cybersecurity",
      content: "Cybersecurity is critical in protecting sensitive data.",
      tags: ["Cybersecurity", "Security"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-22T10:00:00.000Z",
      likes: 20,
      comments: 8,
    },
    {
      id: 7,
      title: "DevOps Practices for Efficiency",
      content: "DevOps bridges the gap between development and operations.",
      tags: ["DevOps", "Efficiency"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-21T10:00:00.000Z",
      likes: 25,
      comments: 10,
    },
    {
      id: 8,
      title: "AI Innovations in Software Development",
      content: "AI is transforming the way software is developed and deployed.",
      tags: ["AI", "Software"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-20T10:00:00.000Z",
      likes: 30,
      comments: 12,
    },
    {
      id: 9,
      title: "Building Scalable Web Applications",
      content: "Scalability is key to handling large user bases effectively.",
      tags: ["Web", "Scalability"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-19T10:00:00.000Z",
      likes: 18,
      comments: 7,
    },
    {
      id: 10,
      title: "The Future of Programming Languages",
      content: "Programming languages are evolving to meet modern challenges.",
      tags: ["Programming", "Languages"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750637522/post-image_j2wwn7.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-18T10:00:00.000Z",
      likes: 22,
      comments: 9,
    },
  ],
  total: 10,
  page: 1,
  lastPage: 1,
};