export const recommendedPosts = {
  data: [
    {
      id: 1,
      title: "5 Reasons to Learn Frontend Development in 2025",
      content: "Frontend development is about crafting user experiences that are fast, accessible, and delightful.",
      tags: ["Programming", "Frontend", "Coding"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750635309/frontend-image_pzqp69.svg",
      author: { id: 1, name: "John Doe", email: "john@example.com" },
      createdAt: "2025-05-27T10:00:00.000Z",
      likes: 20,
      comments: 20,
    },
    {
      id: 2,
      title: "Why Backend Development is Crucial in 2025",
      content: "Backend development ensures the functionality and scalability of web applications.",
      tags: ["Programming", "Backend", "Coding"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633453/cld-sample-3.jpg",
      author: { id: 2, name: "Jane Smith", email: "jane@example.com" },
      createdAt: "2025-05-26T10:00:00.000Z",
      likes: 50,
      comments: 30,
    },
    {
      id: 3,
      title: "The Rise of AI in Software Development",
      content: "Artificial Intelligence is transforming the way software is developed, tested, and deployed.",
      tags: ["AI", "Software", "Development"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633445/samples/landscapes/architecture-signs.jpg",
      author: { id: 3, name: "Alice Johnson", email: "alice@example.com" },
      createdAt: "2025-05-25T10:00:00.000Z",
      likes: 70,
      comments: 40,
    },
    {
      id: 4,
      title: "How to Master Full Stack Development in 2025",
      content: "Full stack development combines frontend and backend skills to create complete web applications.",
      tags: ["Full Stack", "Development", "Coding"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633452/samples/man-on-a-street.jpg",
      author: { id: 4, name: "Michael Brown", email: "michael@example.com" },
      createdAt: "2025-05-24T10:00:00.000Z",
      likes: 35,
      comments: 15,
    },
    {
      id: 5,
      title: "Top 10 Programming Languages to Learn in 2025",
      content: "Discover the top programming languages that will dominate the tech industry in 2025.",
      tags: ["Programming", "Languages", "Tech"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633453/cld-sample-2.jpg",
      author: { id: 5, name: "Emily Davis", email: "emily@example.com" },
      createdAt: "2025-05-23T10:00:00.000Z",
      likes: 60,
      comments: 25,
    },
    {
      id: 6,
      title: "The Future of Cloud Computing in 2025",
      content: "Cloud computing continues to evolve, offering scalability and flexibility for businesses worldwide.",
      tags: ["Cloud", "Computing", "Tech"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633445/samples/ecommerce/leather-bag-gray.jpg",
      author: { id: 6, name: "Chris Evans", email: "chris@example.com" },
      createdAt: "2025-05-22T10:00:00.000Z",
      likes: 45,
      comments: 18,
    },
    {
      id: 7,
      title: "How to Build Scalable Web Applications",
      content: "Learn the best practices for building scalable web applications in 2025.",
      tags: ["Web", "Applications", "Scalability"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633444/samples/people/smiling-man.jpg",
      author: { id: 7, name: "Sophia Lee", email: "sophia@example.com" },
      createdAt: "2025-05-21T10:00:00.000Z",
      likes: 30,
      comments: 12,
    },
    {
      id: 8,
      title: "The Importance of Cybersecurity in 2025",
      content: "Cybersecurity is more critical than ever as threats continue to evolve.",
      tags: ["Cybersecurity", "Tech", "Security"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633445/samples/people/jazz.jpg",
      author: { id: 8, name: "David Miller", email: "david@example.com" },
      createdAt: "2025-05-20T10:00:00.000Z",
      likes: 25,
      comments: 10,
    },
    {
      id: 9,
      title: "The Role of DevOps in Modern Software Development",
      content: "DevOps bridges the gap between development and operations, ensuring faster delivery.",
      tags: ["DevOps", "Software", "Development"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633446/samples/imagecon-group.jpg",
      author: { id: 9, name: "Olivia Taylor", email: "olivia@example.com" },
      createdAt: "2025-05-19T10:00:00.000Z",
      likes: 40,
      comments: 20,
    },
    {
      id: 10,
      title: "The Evolution of Artificial Intelligence in 2025",
      content: "AI continues to revolutionize industries, from healthcare to finance.",
      tags: ["AI", "Tech", "Innovation"],
      imageUrl: "https://res.cloudinary.com/dmesfixqe/image/upload/v1750633446/samples/food/spices.jpg",
      author: { id: 10, name: "Liam Wilson", email: "liam@example.com" },
      createdAt: "2025-05-18T10:00:00.000Z",
      likes: 55,
      comments: 22,
    },
  ],
  total: 10,
  page: 1,
  lastPage: 2,
};